server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      ## Routes for Employee Service
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**

      ## Automatically Create Routes
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

## Add this property when you use discovery locator to automatically create routes
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway:
#            handler:
#              RoutePredicateHandlerMapping: DEBUG

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'